name: Ultramat-Arduino-CI-CD

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Get Release Version
        run: echo "RELEASE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
      - name: Pull Docker image
        run: docker pull kleinspeedy/arduino-cross-builder:latest
      - name: Build code
        run: |
          docker run -v $(pwd):/ultra-arduino kleinspeedy/arduino-cross-builder \
          /bin/bash -c "./bootstrap.sh && ./dewit.sh" 
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: artifacts
          path: build/UltraArduino.*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: UltraArduino.*
          token: ${{ secrets.GITHUB_TOKEN }}
